gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2629800
    ttl_update: true
    user_provider: app_user_provider
    user_identity_field: 'login'
    token_parameter_name: refreshToken  
