controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/token
    schemes: "https"

api_refresh_token:
    path: /api/refresh/token
    schemes: "https"

api_token_refresh:
    path: /api/token-refresh/{refreshToken}/token
    controller: App\Controller\RefreshTokenController::refresh
    methods: [POST]
    schemes: "https"
